[package]
name = "runnt"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
fastrand="1.9.0" #for random
ndarray = "0.15.6" #for matrix

[dev-dependencies]
criterion = "0.4" #for bench
tempfile = "3.3.0" #for test

[[bench]]
name = "iterations"
harness = false