[package]
name = "runnt"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "Easy Neural Network for machine learning"
repository =  "https://github.com/griccardos/runnt/"
readme = "README.md"
keywords = ["reinforcement", "ai","qlearning","machinelearning","learning"]
categories = ["science","algorithms"]

[dependencies]
fastrand="1.9.0" #for random
ndarray = "0.15.6" #for matrix

[dev-dependencies]
criterion = "0.4" #for bench
tempfile = "3.4.0" #for test

[[bench]]
name = "iterations"
harness = false